### ISSUE TITLE
MangaBox > Mangakakalot not working in 0.7 (45)

### ISSUE THREAD

**Issue by PlayingWithPi** [TheNetsky/extensions-mangastream#20]
I cannot see any of the tiles within the repo for Mangakakalot.
Manganato seems to work however?

**Comment by TheNetsky** [comment]
You have not provided any useful information.

Missing:
App version
Source version
Screenshots or video

**Comment by PlayingWithPi** [comment]
> You have not provided any useful information.
> 
> Missing: App version Source version Screenshots or video

App version 0.7 (45) <-- See subject title.
Source version 3.0.6 (nar1n)
Repo URL : https://thenetsky.github.io/extentions-generic/mangabox
Screenshots or video

![Image 2022-06-07 11 25 25 AM](https://user-images.githubusercontent.com/82283945/172358232-f9d4fdc8-079f-4798-8361-2bbeae6ba12a.jpeg)

**Comment by TheNetsky** [comment]
There should be an error mesage, I assume you have them disabled.

Also click the little cloud icon and see if it loads there.

**Comment by PlayingWithPi** [comment]
> There should be an error mesage, I assume you have them disabled.
> 
> Also click the little cloud icon and see if it loads there.

Thanks for that, I did have the error code disabled. Have enabled now. (see image below)

I've clicked the cloud icon and this seems to work/display the webpage correctly.

![Image 2022-06-07 11 43 25 AM](https://user-images.githubusercontent.com/82283945/172361497-de6eacb2-796a-4820-9075-40c6be73f3ad.jpeg)

**Comment by TheNetsky** [comment]
That error is unrelated to what you're experiencing, any other error?

**Comment by PlayingWithPi** [comment]
To further note.. 
I have just gone from App version 0.7 (38) to 0.7 (45) in one jump.

**Comment by PlayingWithPi** [comment]
![Image 2022-06-07 11 48 32 AM](https://user-images.githubusercontent.com/82283945/172362022-1a3a2933-4eb0-4cba-9954-50007b670f0c.jpeg)

**Comment by PlayingWithPi** [comment]
attached to this message is my apps logs.
[07-06.Paperback.txt](https://github.com/TheNetsky/extensions-mangastream/files/8852511/07-06.Paperback.txt)

**Comment by TheNetsky** [comment]
Do you have any experimental settings enabled?

**Comment by PlayingWithPi** [comment]
just the legacy reader & Legacy Manga Viewer.
I've tried turning on/off Async Sources and nothing changes.

**Comment by TheNetsky** [comment]
For starters, do NOT use async option. Try reinstalling, this is definitely something on your end.

**Comment by PlayingWithPi** [comment]
seems to be something getting corrupted along the way, re-install fixed this.
Thanks for the quick support 👍🏼 

Would say to have a form/template of info you would like to see incase of issues that occur for future people !

**Comment by TheNetsky** [comment]
Haven't had the time to do that, Discord is easier

**Comment by PlayingWithPi** [comment]
Cannot message on Discord. At all.
All of the channels state "You don't have permission to send messages in this channel" or "Follow to get this channel's update in your own server".

**Comment by TheNetsky** [comment]
You have to pass the test to be able to do that, up to you to find it. Might require some reading. :)

**Comment by PlayingWithPi** [comment]
i read the secret message XD
Sneaky sneaky.
