### ISSUE TITLE
Can’t update my titles

### ISSUE THREAD

**Issue by leosales9** [TheNetsky/extensions-mangastream#25]
Sorry to bother you guys but I can’t update my titles, when I try this error appears. I tried to reinstall the source but that didn’t work.

I appreciate your efforts 
![FE2523E8-1E20-4FF4-9942-9C135DFC4D6A](https://user-images.githubusercontent.com/74514720/176183102-549ade47-af19-4039-b6ac-b783e045b0dc.jpeg)

**Comment by TheNetsky** [comment]
Requires additional information
