### ISSUE TITLE
Cloudflare bypass broke for Sushi Scan repo

### ISSUE THREAD

**Issue by Overfloow** [TheNetsky/extensions-mangastream#31]
Sushi scan doesn't work anymore because the Cloudflare bypass isn't working. The webpage is stuck on the message "Checking if the site connection is secure", it seems like the page reload every few seconds.

I use Paperback v0.7-r46, dowloaded from the official app store on a iPhone and a iPad.

Sushi Scan source have been added from MangaStream Extensions (0.6)

1. Go to 'External Sources'
2. Click on 'Sushi Scan'
3. Click on 'Cloudflare Bypass'

**Comment by TheNetsky** [comment]
Nothing we can do, wait till 0.8 or use another source.
