### ISSUE TITLE
Some source don’t display anything after update

### ISSUE THREAD

**Issue by Than17l4** [TheNetsky/extensions-mangastream#37]
**Describe the bug**
three of my source extensions don’t show anything after the latest update “0.8.1” don’t know if the problem is repo or source

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
![78B93032-4BC1-4EE2-8385-A92C7F43E104](https://github.com/TheNetsky/extensions-mangastream/assets/105532762/bc1cbfdf-c505-4ee4-b5a6-9d75d173cf83)
![2A6DA8AF-5787-45E3-B27A-F5C2936BF94A](https://github.com/TheNetsky/extensions-mangastream/assets/105532762/0499d499-dad2-444c-a4b3-b2ab5dddb3e2)
![DB1B1F1C-ECF5-45A4-9204-B258AF1A8BC1](https://github.com/TheNetsky/extensions-mangastream/assets/105532762/b4a5a7d0-aa86-406f-98f6-4e9769a390ae)

**App version**
- v0.8.1-r3

**Source WITH source version**
- mangakakalot (4.0.3), manganato (4.0.4), and mangabat (4.0.3)

**Additional context**

**Comment by TheNetsky** [comment]
Reinstall app.
